resolver: ghcjs-0.2.0.20151029_ghc-7.10.2

# Local packages, usually specified by relative directory name
packages:
- '.'
- '../webapicors/webapi'

# Packages to be pulled from upstream that are not in the resolver (e.g., acme-missiles-0.3)
extra-deps:
- reflex-0.4.0
- reflex-dom-0.3
- bifunctors-5.2.1
- data-default-0.5.3
- dependent-map-0.2.1.0
- dependent-sum-0.3.2.1
- dependent-sum-template-0.0.0.4
- exception-transformers-0.4.0.3
- ghcjs-dom-0.2.3.1
- haskell-src-exts-1.16.0.1
- haskell-src-meta-0.6.0.13
- lens-4.13.2
- ref-tf-0.4
- safe-0.3.9
- semigroups-0.18.1
- these-0.6.2.1
- transformers-compat-0.5.1.4
- base-orphans-0.5.1
- comonad-5
- contravariant-1.4
- cpphs-1.19.3
- data-default-class-0.0.1
- data-default-instances-base-0.0.1
- data-default-instances-containers-0.0.1
- data-default-instances-dlist-0.0.1
- data-default-instances-old-locale-0.0.1
- distributive-0.5.0.2
- exceptions-0.8.2.1
- free-4.12.4
- kan-extensions-5.0.1
- profunctors-5.2
- reflection-2.1.2
- semigroupoids-5.0.1
- tagged-0.8.3
- th-extras-0.0.0.2
- th-orphans-0.13.0
- void-0.7.1
- StateVar-1.1.0.3
- adjunctions-4.3
- polyparse-1.11
- prelude-extras-0.4.0.3
- th-lift-0.7.6
- th-reify-many-0.1.4
- th-expand-syns-0.3.0.6
- freer-0.2.2.4
# - webapi-0.2.0.0
- rank1dynamic-0.3.2.0

# WEBAPI
- QuickCheck-2.8.2
- blaze-builder-0.4.0.1
- bytestring-lexing-0.5.0.2
- bytestring-trie-0.2.4.1
- cookie-0.4.1.6
- http-client-0.4.27
- http-client-tls-0.2.2
- http-media-0.6.3
- http-types-0.8.6
- network-uri-2.6.0.3
- resourcet-1.1.7.3
- wai-3.0.5.0
- wai-extra-3.0.14.1
- ansi-terminal-0.6.2.3
- base64-bytestring-1.0.0.1
- bytestring-builder-0.10.6.0.0
- connection-0.2.5
- fast-logger-2.4.1
- iproute-1.7.0
- lifted-base-0.2.3.6
- mime-types-0.1.0.6
- mmorph-1.0.6
- monad-control-1.0.0.5
- network-2.6.2.1
- parsec-3.1.9
- random-1.1
- streaming-commons-0.1.15.2
- stringsearch-0.3.6.6
- tf-random-0.5
- tls-1.3.4
- transformers-base-0.4.4
- unix-compat-0.4.1.4
- vault-0.3.0.6
- wai-logger-2.2.5
- word8-0.1.2
- zlib-0.6.1.1
- appar-0.1.4
- asn1-encoding-0.9.3
- asn1-types-0.3.2
- auto-update-0.1.3
- byteable-0.1.1
- byteorder-1.0.4
- cereal-0.5.1.0
- cryptonite-0.13
- easy-file-0.2.1
- memory-0.11
- socks-0.5.4
- unix-time-0.3.6
- x509-1.6.3
- x509-store-1.6.1
- x509-system-1.6.3
- x509-validation-1.6.3
- asn1-parse-0.9.4
- hourglass-0.2.10
- pem-0.2.2

compiler: ghcjs-0.2.0.20160107_ghc-7.10.2
compiler-check: match-exact
setup-info:
 ghcjs:
  source:
   ghcjs-0.2.0.20160107_ghc-7.10.2:
    url: "http://ghcjs.luite.com/master-20160107.tar.gz"
