resolver: lts-5.15
extra-deps:
- ghcjs-dom-0.2.3.1
- rank1dynamic-0.3.2.0
- reflex-0.4.0
- reflex-dom-0.3
- ref-tf-0.4
- these-0.6.2.1
- haskell-src-exts-1.16.0.1
- http-types-0.8.6
- webapi-0.2.2.0

compiler: ghcjs-0.2.0.20160416_ghc-7.10.2
compiler-check: match-exact
setup-info:
  ghcjs:
    source:
      ghcjs-0.2.0.20160416_ghc-7.10.2:
        url: "http://ghcjs.luite.com/master-20160416.tar.gz"
